### ISSUE TITLE
标签手动输入区不能通过左右方向键移动光标

### ISSUE THREAD

**Issue by Hongjing0506** [zzlb0224/zotero-annotation-manage#16]
在【添加标签】时，如果手动输入新的tag，光标在输入栏中不能被左右方向键控制移动，只能用鼠标点击相应的位置。

希望可以增加光标通过方向键左右移动的功能！十分感谢！

**Comment by zzlb0224** [comment]
可能是事件keyup 引起的，
猜测换成keydown或者keypress可以解决，
下次更新

**Comment by zzlb0224** [comment]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/b9e0cd83-4d1c-47b6-8c1b-849f3c5ab941)

鼠标移动和区域选择

**Comment by Hongjing0506** [comment]
已修复，谢谢！
