### ISSUE TITLE
【添加标签】时，能否将刚使用过的tag排在前面

### ISSUE THREAD

**Issue by Hongjing0506** [zzlb0224/zotero-annotation-manage#17]
目前【添加标签】页面，最开头是固定tag。后面的tag似乎是按照已使用次数进行排序的。

但是实际情况是一篇文献中，有些刚使用过的tag，在下几个annotations中又会再次使用。重复搜索有点麻烦。

不知能否增加【把刚使用过的tag】排在固定tag后的功能。

或者排序是：固定tag-本篇文献使用过的tag-其他tag

谢谢！

**Comment by zzlb0224** [comment]
这两个都可以加上，
- 本篇置顶
- 最近使用的n个

**Comment by Hongjing0506** [comment]
有了，谢谢！

**Comment by Hongjing0506** [comment]
有了，谢谢！
