### ISSUE TITLE
和 Translate for Zotero一起使用时，弹窗的大小无法控制，需要在启用aotero-annotation-manage前先调整好弹窗的宽度，不然会超出屏幕显示范围

### ISSUE THREAD

**Issue by beib233** [zzlb0224/zotero-annotation-manage#20]
和 Translate for Zotero一起使用时，弹窗的大小无法控制，需要在启用aotero-annotation-manage前先调整好弹窗的宽度，不然会超出屏幕显示范围

**Comment by zzlb0224** [comment]
我现在就是做了 maxWidth限制和MaxHeight限制。

对我来说获取窗口高度、宽度和定位太难了。
有什么办法处理吗？

**Comment by zzlb0224** [comment]
我考虑做个延时加载。等他们在加载完了，我再获取位置，进行页面更新

**Comment by zzlb0224** [comment]
做了个延时加载，还超吗？

**Comment by kdqiu** [comment]
> 做了个延时加载，还超吗？
你好，谢谢你的插件，对我帮助很大，弹窗问题还是偶尔会存在。麻烦你能再次调整一下吗
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/36355661/864040ea-1ae8-41ca-83c1-23301596dbec)

**Comment by zzlb0224** [comment]
是不是这样？

pdf缩放比例比较大的，容易超出？

我试试改改这个问题
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/810a9485-d257-4990-b60a-c3490fa563c5)

**Comment by zzlb0224** [comment]
> > 做了个延时加载，还超吗？
> 
> 你好，谢谢你的插件，对我帮助很大，弹窗问题还是偶尔会存在。麻烦你能再次调整一下吗 ![image](https://private-user-images.githubusercontent.com/36355661/324384079-864040ea-1ae8-41ca-83c1-23301596dbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODAxMjEsIm5iZiI6MTcxMzc3OTgyMSwicGF0aCI6Ii8zNjM1NTY2MS8zMjQzODQwNzktODY0MDQwZWEtMWFlOC00MWNhLTgzYzEtMjMzMDE1OTZkYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA5NTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZDQ3NjY4MzFiMWUzMTZjOTE1ZWQwZjllOTJlZDRjOTZiMDg5ZTI2OTk0ZjVhZWE0M2UwOTM2MjM0YjJjNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2CirJ-HkZzqqGiBOjBByBYU7vOQCtCGBA4L1knGc65U)

更新了

**Comment by kdqiu** [comment]
> 是不是这样？
> 
> pdf缩放比例比较大的，容易超出？
> 
> 我试试改改这个问题 ![image](https://private-user-images.githubusercontent.com/8912444/324389464-810a9485-d257-4990-b60a-c3490fa563c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODY1MzUsIm5iZiI6MTcxMzc4NjIzNSwicGF0aCI6Ii84OTEyNDQ0LzMyNDM4OTQ2NC04MTBhOTQ4NS1kMjU3LTQ5OTAtYjYwYS1jMzQ5MGZhNTYzYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjJUMTE0MzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2IyNmUyODNjZjUyN2ZiMGNkMDZhM2RhODc4NmUyYTFlODI4YTI5NWUyZjMzY2YzY2E4MWRkYjAxMmUxMDUxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fr6qYAG-lwB0pVJ9HeLMpv3-Z46aRshh3PFgH794bqY)

是的，我一般会放到最大，有时候就会溢出到外面

**Comment by kdqiu** [comment]
> > > 做了个延时加载，还超吗？
> > 
> > 
> > 你好，谢谢你的插件，对我帮助很大，弹窗问题还是偶尔会存在。麻烦你能再次调整一下吗 ![image](https://private-user-images.githubusercontent.com/36355661/324384079-864040ea-1ae8-41ca-83c1-23301596dbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODAxMjEsIm5iZiI6MTcxMzc3OTgyMSwicGF0aCI6Ii8zNjM1NTY2MS8zMjQzODQwNzktODY0MDQwZWEtMWFlOC00MWNhLTgzYzEtMjMzMDE1OTZkYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA5NTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZDQ3NjY4MzFiMWUzMTZjOTE1ZWQwZjllOTJlZDRjOTZiMDg5ZTI2OTk0ZjVhZWE0M2UwOTM2MjM0YjJjNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2CirJ-HkZzqqGiBOjBByBYU7vOQCtCGBA4L1knGc65U)
> 
> 更新了

好的，感谢🙏，辛苦，我马上去试一试

**Comment by kdqiu** [comment]
> > > 做了个延时加载，还超吗？
> > 
> > 
> > 你好，谢谢你的插件，对我帮助很大，弹窗问题还是偶尔会存在。麻烦你能再次调整一下吗 ![image](https://private-user-images.githubusercontent.com/36355661/324384079-864040ea-1ae8-41ca-83c1-23301596dbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODAxMjEsIm5iZiI6MTcxMzc3OTgyMSwicGF0aCI6Ii8zNjM1NTY2MS8zMjQzODQwNzktODY0MDQwZWEtMWFlOC00MWNhLTgzYzEtMjMzMDE1OTZkYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA5NTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZDQ3NjY4MzFiMWUzMTZjOTE1ZWQwZjllOTJlZDRjOTZiMDg5ZTI2OTk0ZjVhZWE0M2UwOTM2MjM0YjJjNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2CirJ-HkZzqqGiBOjBByBYU7vOQCtCGBA4L1knGc65U)
> 
> 更新了

你好大佬，更新到最新0.5.9后，解决了左边溢出的问题，右边还是会出现溢出。我在多篇文档中都试了一下，右边还是会存在。
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/36355661/31969a47-75dd-4128-a871-092ec2afeccd)
