### ISSUE TITLE
固定颜色和 固定标签似乎改变颜色代码对应的标签也不会变成相应的颜色

### ISSUE THREAD

**Issue by oushiei120** [zzlb0224/zotero-annotation-manage#21]
<img width="475" alt="图片" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/842b1537-296e-4ded-ad9a-165cc898e72f">
一直是这几个颜色循环

**Comment by zzlb0224** [comment]
可以在这里设置更多的颜色。
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/6535c782-2bbe-428f-a671-d3a50120e59f)

**Comment by zzlb0224** [comment]
你看增加了添加随机颜色和删除颜色的功能可以吗？

**Comment by oushiei120** [comment]
现在可以了！！非常喜欢这个插件，为你打 call！！！
