### ISSUE TITLE
无法使用抽取标签的功能，点了没有反应 ，是因为 betternotes 的原因吗

### ISSUE THREAD

**Issue by oushiei120** [zzlb0224/zotero-annotation-manage#25]
<img width="240" alt="image" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/b178212a-89cf-4056-974d-e7cf6c665db2">
无法使用抽取标签的功能，点了没有反应 ，是因为 betternotes 的原因吗

**Comment by oushiei120** [comment]
点了没有反应

**Comment by zzlb0224** [comment]
是这个功能吗？我删除了一个函数，现在恢复了

![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/093d9d6d-808e-450b-aae0-4609b59e70d3)

**Comment by oushiei120** [comment]
<img width="570" alt="image" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/fc064383-9725-48ee-b399-13dc2f2b046e">
感谢～现在这个功能可以了 ，但是上面的两个无法使用、
<img width="212" alt="image" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/60a817c0-5b29-4555-ad5e-9539bdbf4658">

**Comment by zzlb0224** [comment]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/4070f473-8e3f-4ef8-81c8-0930840438d8)
看起来可以啊

需要在有笔记的目录

**Comment by zzlb0224** [comment]
不懂你的意思

**Comment by oushiei120** [comment]
就是把颜色标签直接固定在PDF 浏览界面的最上面

**Comment by zzlb0224** [comment]
这些放到上面？


![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/7dae1211-9e6d-4c3c-97b5-915f48e6bf16)

**Comment by oushiei120** [comment]
直接放在上面，一行

**Comment by zzlb0224** [comment]
上面内容我不知道怎么加另外我的标签太多了，不适合放在那里还有标签是动态加载的，长度不固定周利斌周口师范学院 | Email: ***@***.*** | Tel: +08615690820302

**Comment by oushiei120** [comment]
还有就是是否可以自主设定输出笔记的格式？
<img width="476" alt="image" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/c1c7b91c-1af6-4c34-9503-de5ebe1666c0">
 例如这里有一级标题和正文的部分，那我想把正文（也就是注释的部分）加上一个# 作为二级标题，这样可行吗

**Comment by zzlb0224** [comment]
这是可行的，我后续加个选项吧
应该还会加 输出排序
我还没想好

**Comment by oushiei120** [comment]
好的，谢谢～特别优秀的插件！！期待！！期待后期标签导出可以自定义

**Comment by zzlb0224** [comment]
你可以把自己对笔记导出的想法说一下

**Comment by oushiei120** [comment]
最好是和 betternotes 的笔记模版相结合 ，这样可以减少用户学习的成本

**Comment by oushiei120** [comment]
因为zotero 的有很多文件夹，能不能增加一个按照群组设置标签的功能呀？现在标签太多了，很容易眼花呜呜！！

**Comment by oushiei120** [comment]
因为不同的文件夹本身就具有一定程度上的学科属性，可以设置一个所有文件通用的标签组，然后用户可以根据自己对于其他分类进行自行加入其他标签。这样在写综述的时候就不会怕，一右键就跳出来很多其他文件夹下的学科标签

**Comment by zzlb0224** [comment]
> zotero 的有很多文件夹，能不能增加一个按

这样能实现你想要的功能
1、选中一个文件夹
2、取消与全部文件夹相关
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/1cbe2dc2-fd09-415f-a45d-acf22dc8ed09)

**Comment by oushiei120** [comment]
然后现在，有点问题，我不知道是不是这个插件的问题，有时候会突然无法做注释，不会跳出右键框，然后关闭 pdf 标签页再打开，刚才做的所有的注释都会消失………………

**Comment by zzlb0224** [comment]
> 最好是和 betternotes 的笔记模版相结合 ，这样可以减少用户学习的成本

非常好的建议

**Comment by zzlb0224** [comment]
> 然后现在，有点问题，我不知道是不是这个插件的问题，有时候会突然无法做注释，不会跳出右键框，然后关闭 pdf 标签页再打开，刚才做的所有的注释都会消失………………

因为我是自己也在做笔记，所以有问题直接就改了。
目前还没碰到你说的这个问题

**Comment by oushiei120** [comment]
现在无法导出注释。。。。
<img width="221" alt="image" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/8fef2245-9325-47f4-b915-a7445c37f08f">

这四个功能全部消失 ，配置是mac os

最后一个功能标签重复出现
<img width="147" alt="image" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/18c416ba-df65-47c9-9259-824b403fce76">

**Comment by oushiei120** [comment]
不知道您有没有遇到过这样的问题：标签特别多，学科特别多，所以这部分修改起来眼花缭乱的，真的希望分几个组。
<img width="554" alt="image" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/4e6abbf0-ab10-4399-a9ad-1ad34e1f7ddd">
最好是可以选择collection 然后让其选择对应的标签组

**Comment by zzlb0224** [comment]
你说的功能不是很复杂。就是做出来实用不？

**Comment by oushiei120** [comment]
我现在有这样的问题： 有时候加标签会导致突然这部分变为灰色，右键无法弹出标签框。为了避免这样，我直接选择使用画横线模式（这样颜色都是一种）然后统一在左侧加标签，可惜这样的注释是无法导出的。
<img width="440" alt="image" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/8ab996c8-3873-4052-af77-a156149c9284">


<img width="243" alt="image" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/f05a75ed-4ee2-4b19-96a8-2be7144c7805">

**Comment by oushiei120** [comment]
<img width="379" alt="image" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/a9ab3233-0f6a-4f2f-b5a9-c0956c7c4402">
显示如上图所示

**Comment by oushiei120** [comment]
不知道是我自己的问题还是什么，有时候做标签的时候，突然那些工具栏就会变成灰色，我停用了除了 betternotes 以外的所有插件，依然无法解决

**Comment by zzlb0224** [comment]
ink 类型笔记导出好像没有做

**Comment by zzlb0224** [comment]
> 不知道是我自己的问题还是什么，有时候做标签的时候，突然那些工具栏就会变成灰色，我停用了除了 betternotes 以外的所有插件，依然无法解决

这个不清楚原因
