### ISSUE TITLE
设置里面两个 标签管理  设置项

### ISSUE THREAD

**Issue by jlu511** [zzlb0224/zotero-annotation-manage#26]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/64378673/d5a9ce8e-1cc9-45c0-867e-bf41f613b16e)

beta74   0.4.35

**Comment by zzlb0224** [comment]
谢谢，已修复

**Comment by jlu511** [comment]
> 谢谢，已修复

感谢修复
