### ISSUE TITLE
更新到最新0.5.9后，解决了左边溢出的问题，右边还是会出现溢出。我在多篇文档中都试了一下，右边还是会存在。

### ISSUE THREAD

**Issue by zzlb0224** [zzlb0224/zotero-annotation-manage#27]
新开一个issue。
我测试一下

              > > > 做了个延时加载，还超吗？
> > 
> > 
> > 你好，谢谢你的插件，对我帮助很大，弹窗问题还是偶尔会存在。麻烦你能再次调整一下吗 ![image](https://private-user-images.githubusercontent.com/36355661/324384079-864040ea-1ae8-41ca-83c1-23301596dbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODAxMjEsIm5iZiI6MTcxMzc3OTgyMSwicGF0aCI6Ii8zNjM1NTY2MS8zMjQzODQwNzktODY0MDQwZWEtMWFlOC00MWNhLTgzYzEtMjMzMDE1OTZkYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA5NTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZDQ3NjY4MzFiMWUzMTZjOTE1ZWQwZjllOTJlZDRjOTZiMDg5ZTI2OTk0ZjVhZWE0M2UwOTM2MjM0YjJjNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2CirJ-HkZzqqGiBOjBByBYU7vOQCtCGBA4L1knGc65U)
> 
> 更新了

你好大佬，更新到最新0.5.9后，解决了左边溢出的问题，右边还是会出现溢出。我在多篇文档中都试了一下，右边还是会存在。
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/36355661/31969a47-75dd-4128-a871-092ec2afeccd)

_Originally posted by @kdqiu in https://github.com/zzlb0224/zotero-annotation-manage/issues/20#issuecomment-2069207296_

**Comment by kdqiu** [comment]
> 新开一个issue。 我测试一下
> 
> ```
>           > > > 做了个延时加载，还超吗？
> ```
> 
> > > 你好，谢谢你的插件，对我帮助很大，弹窗问题还是偶尔会存在。麻烦你能再次调整一下吗 ![image](https://private-user-images.githubusercontent.com/36355661/324384079-864040ea-1ae8-41ca-83c1-23301596dbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODAxMjEsIm5iZiI6MTcxMzc3OTgyMSwicGF0aCI6Ii8zNjM1NTY2MS8zMjQzODQwNzktODY0MDQwZWEtMWFlOC00MWNhLTgzYzEtMjMzMDE1OTZkYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA5NTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZDQ3NjY4MzFiMWUzMTZjOTE1ZWQwZjllOTJlZDRjOTZiMDg5ZTI2OTk0ZjVhZWE0M2UwOTM2MjM0YjJjNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2CirJ-HkZzqqGiBOjBByBYU7vOQCtCGBA4L1knGc65U)
> > 
> > 
> > 更新了
> 
> 你好大佬，更新到最新0.5.9后，解决了左边溢出的问题，右边还是会出现溢出。我在多篇文档中都试了一下，右边还是会存在。 ![image](https://private-user-images.githubusercontent.com/36355661/324449332-31969a47-75dd-4128-a871-092ec2afeccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODgxMjksIm5iZiI6MTcxMzc4NzgyOSwicGF0aCI6Ii8zNjM1NTY2MS8zMjQ0NDkzMzItMzE5NjlhNDctNzVkZC00MTI4LWE4NzEtMDkyZWMyYWZlY2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDEyMTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZGQ0ZWZmZGNjOGNmNTY0NjYwYWNmYTVjMmU0NzM2ZmZjZWZlMWI3ZWY2ODYyM2FjMjEyNmQwMjQ2NTA4ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TZgqXyU8m6EoOR7XldUIwHT-3fWKeBFEljgyDj43VjU)
> 
> _Originally posted by @kdqiu in [#20 (comment)](https://github.com/zzlb0224/zotero-annotation-manage/issues/20#issuecomment-2069207296)_

Sorry，没有测试完全，在分为左右两列的PDF中，左边还是可能会出现溢出。
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/36355661/113ebc74-db0d-4b94-89c1-6b1f3f0beb40)

**Comment by zzlb0224** [comment]
doi发给我

**Comment by kdqiu** [comment]
> doi发给我

https://doi.org/10.1007/s11747-024-01002-3

**Comment by zzlb0224** [comment]
检查出来一个bug，关于右边定位的，已经调整了，我自己也在测试
