### ISSUE TITLE
还是希望有一个标签组分类整理的功能

### ISSUE THREAD

**Issue by oushiei120** [zzlb0224/zotero-annotation-manage#28]
我们写论文的时候，整理文献，是具有目的性的
根据每篇文章的构成，会分不同的区域，比如说 XX 研究综述，XX 学的研究方法、XX 研究的缺陷
如果写的文章跨度大，会导致标签数量变的非常多，
所以非常想有一个标签集合的概念，
A:XX研究方法，#88888，XX 研究缺陷，#88888
A:BB研究方法，#88888，BB研究缺陷，#88888

根据不同的分组我们可以自由选取不同组的标签

**Comment by zzlb0224** [comment]
这个整理是放在导出的时候吗？

能不能具体说下使用场景和UI建议

**Comment by oushiei120** [comment]
设置一个按钮，按照组别设置标签， 下拉选项（这些选项就是 zotero 文献里的小组、collection）然后点开后按照原来的下图部分来添加相应组的标签。然后在 pdf 注释的时候也只出现这些标签
<img width="241" alt="image" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/d1c1ad3a-59cb-4fae-88dc-093604e50338">

**Comment by zzlb0224** [comment]
按文件夹设置固定标签是吧
我想想怎么实现比较容易

**Comment by oushiei120** [comment]
对的，随着文献量的增多，标签数量是很严重的问题，我觉得必须想个办法分区

**Comment by oushiei120** [comment]
实在不容易做到的话，可以这样：就在 添加标签和颜色窗口的地方放上 不同的组，然后用户手动调整，手动设置我想用的标签组

**Comment by zzlb0224** [comment]
准备对应到分类里，还在调整中

**Comment by oushiei120** [comment]
https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/07eebb56-4fa4-4295-bee3-b031de6b1132


感觉标签多了出现问题也多，所以还是对应分组用对应分组的标签比较好， 例如我现在用的是别的组之前建立的标签，因为这个组之前没有用过这个标签，所以不会被保存下载，然后导致后面功能失效，如视频所示。希望分组标签能解决这个问题

**Comment by oushiei120** [comment]
注意，打标签后 ，所以pdf 的标注、高亮、按钮全部 变白色了，高亮后也不会弹出应用

**Comment by zzlb0224** [comment]
已更新
