### ISSUE TITLE
从网页导入文献时zotero卡死问题

### ISSUE THREAD

**Issue by Hongjing0506** [zzlb0224/zotero-annotation-manage#30]
出现的问题如题。
我使用的zotero版本是：7.0.0-beta.77+adaa61f2c (64-bit)

目前进行了一轮插件之间的冲突性测试，发现：
1、单独打开zotero-annotation-manage的时候能正常运行。
2、打开zotero-annotation-manage、Better notes、Ethereal Style、Zotmoov、zotero GPT、Jasminum时能正常运行
3、当打开zotero-annotation-manage、Zotero GPT、Better Notes、Ethereal Style、Jasminum、Zotero Translate和Zotmoov的时候，从网页导入文献会发生卡顿，表现为此时无法点开zotero窗口或能点开zotero窗口但无法进行操作，要等一段时间（时间不长，但是如果再添加其他插件的话，就会卡得厉害）才能恢复正常运行。

推测是zotero translate和annotation-manage之间是否存在冲突而导致了卡顿？

请问是否能对插件进行适当速度优化？非常感谢！

**Comment by zzlb0224** [comment]
重新检查了代码，并没有和导入文献相关的函数。

会继续关注速度问题。感谢提出。
