### ISSUE TITLE
Crash on PDF Annotation: Compatibility Issue with Zotero Reading List Plugin

### ISSUE THREAD

**Issue by thangnguyenxtz** [zzlb0224/zotero-annotation-manage#32]
Zotero version: 7.0.0-beta.77+adaa61f2c (64-bit)
Plug-in version: 0.5.27

Hi, I've encountered a problem with your plugin while annotating PDF files in Zotero. The application crashes, and my initial checks indicate a compatibility issue with the Zotero Reading List plugin (https://github.com/Dominic-DallOsto/zotero-reading-list) I am currently using. I have disabled all plugins and am re-enabling them one by one to identify the exact cause. Could you please look into this matter?
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/160583202/0f5bb2c3-30f9-43fd-b8ff-b44f31317f8e)

**Comment by zzlb0224** [comment]
I will install zotero-reading-list to check this issue.

**Comment by thangnguyenxtz** [comment]
Thanks, I'm looking forward to hear from you

**Comment by zzlb0224** [comment]
After a few days of testing, I did not get this.
