### ISSUE TITLE
窗口冲突

### ISSUE THREAD

**Issue by mo-qc** [zzlb0224/zotero-annotation-manage#33]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/64970388/f05e358c-f854-4f8a-b7eb-bba76e04a693)
希望解决一下与translate插件的窗口冲突，有时弹窗会变得非常长，或者显示不完整

**Comment by zzlb0224** [comment]
是不希望太宽？

**Comment by mo-qc** [comment]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/64970388/a3b02ae8-378d-4afc-a5ea-803ca31df01f)
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/64970388/7db2191b-733b-43b0-866f-a5cccbd1a5f9)
如图，

**Comment by zzlb0224** [comment]
遮住问题我最近处理过。你现在是不是最新版本？

**Comment by mo-qc** [comment]
> 遮住问题我最近处理过。你现在是不是最新版本？

![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/64970388/310bec1f-b257-47dd-b973-d9176356f7ce)
0.5.32最新版本

**Comment by zzlb0224** [comment]
我关注一下这个问题

**Comment by mo-qc** [comment]
> 我关注一下这个问题
谢谢

**Comment by zzlb0224** [comment]
增加了 当不显示相关标签的时候，宽度不需要扩展。也就是跟随translate的宽度

**Comment by mo-qc** [comment]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/64970388/f3179a92-ee37-465f-8ab8-22268561666e)
还有会有超长的问题，能不能让始终跟随translate的宽度

**Comment by Geo123abc** [comment]
> ![image](https://private-user-images.githubusercontent.com/64970388/332640811-a3b02ae8-378d-4afc-a5ea-803ca31df01f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzgyNDAsIm5iZiI6MTcxNjM3Nzk0MCwicGF0aCI6Ii82NDk3MDM4OC8zMzI2NDA4MTEtYTNiMDJhZTgtMzc4ZC00YWZjLWE1ZWEtODAzY2EzMWRmMDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDExMzkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxOTc4OGJjNGJlZmI4MGRhZjQzYmFjZDdmZTk0Y2NlMWRiMTlkZmZkNTU0ODkyOTZiZjJjZjllM2E4NWI5OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kzB4CH0zmgGWy-ER8SykDd-O1O11EQurQyk1p9O3yzs) ![image](https://private-user-images.githubusercontent.com/64970388/332640818-7db2191b-733b-43b0-866f-a5cccbd1a5f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzgyNDAsIm5iZiI6MTcxNjM3Nzk0MCwicGF0aCI6Ii82NDk3MDM4OC8zMzI2NDA4MTgtN2RiMjE5MWItNzMzYi00M2IwLTg2NmYtYTVjY2NiZDFhNWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDExMzkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2OWIzMjIyNmQ3ZjA1OGVlZDExOTY1ODJmMDk4YzFkOWM5ODcxMjIxMTE5OGVhM2YzM2IyYWE2ZTBkM2IyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i4lgXfoA2GV4lu0Rv0KilY95LjpMCR-8V10ZzIPtxfo) 如图，

你这张截图红框右下角的那些斜道处，你鼠标放在这里，鼠标变形之后拖动一下，改一下窗口大小，看看能不能有所改善。

**Comment by zzlb0224** [comment]
楼上 @Geo123abc  说的有道理。

你 @mo-qc  是不是翻译开了固定大小？

**Comment by zzlb0224** [comment]
固定大小可能会越界

**Comment by zzlb0224** [comment]
更新了版本  当翻译采用固定大小的时候，跟随它

**Comment by mo-qc** [comment]
> 固定大小可能会越界

没有开启固定大小

> 更新了版本 当翻译采用固定大小的时候，跟随它

好的

**Comment by zzlb0224** [comment]
因为我的窗口行为改变了翻译的窗口大小，使用他的代码修复一下

**Comment by zzlb0224** [comment]
已修复，测试之后没有问题
