### ISSUE TITLE
刚刚的版本有点奇怪，请看 VCR

### ISSUE THREAD

**Issue by oushiei120** [zzlb0224/zotero-annotation-manage#34]
https://github.com/zzlb0224/zotero-annotation-manage/assets/86762134/3501bd68-7e87-49a4-98f6-0dec381a0485

**Comment by zzlb0224** [comment]
我测试的时候发现了这个问题，后来改着改着忘了，晚点修复

**Comment by zzlb0224** [comment]
更新了
