### ISSUE TITLE
能否增加功能进行颜色批注时自动添加对应颜色的备注标签？

### ISSUE THREAD

**Issue by Kaergo** [zzlb0224/zotero-annotation-manage#37]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/54634271/1226c774-9fc1-41d1-a5c7-1a32399bf5cf)
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/54634271/7d9e686b-f63c-46e2-b11f-6347c177dcc1)

**Comment by zzlb0224** [comment]
我知道你要什么，因为这也是我最开始的追求，致敬Zotero-Style。他的修改标注颜色非常有用。

但是这样会影响系统事件，不建议这么做

因此，我把这个分成了两部分。保留以前的颜色，还增加了，如果颜色一直就显示一个可点击的按钮


![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/57439318-d724-46fb-9a81-53081bfe1651)

**Comment by zzlb0224** [comment]
颜色数字完全匹配才能出现下面的标签

颜色可以从标注里面找到

![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/cfd665d9-79c9-4d81-8781-61afec425a57)

**Comment by Kaergo** [comment]
好的 谢谢

**Comment by zzlb0224** [comment]
增加了配置，记得启用

![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/ee92b23c-5692-47f4-9e24-129cf5c57412)
