### ISSUE TITLE
阅读界面划词闪退

### ISSUE THREAD

**Issue by wuyan0808** [zzlb0224/zotero-annotation-manage#38]
PDF阅读界面划词有几率闪退，似乎和translate插件有冲突，只保留这两个插件能稳定复现闪退的情况。刚打开zotero软件第一次划词闪退的几率很高，重启软件后一般就正常了（不会再闪退，两个插件的功能均能正常使用）。目前有稳定的复现步骤，在能正常使用划词的情况下，启用调试日志，清空一次输出日志，再重新划词，能够稳定闪退。
怀疑是不是窗口大小的问题引起的？
两个插件的版本目前都是最新的，这个闪退问题在之前的版本中就有出现，不过没有发现稳定的触发方式，以及开启调试日志的情况下zotero闪退的瞬间也没有看到有什么信息，因此没有提交问题。现在发现能稳定触发bug的方式，故提交一下，希望大佬能看一下是什么情况。
zotero-annotation-manage 插件版本 0.6.6
translate for zotero 插件版本 1.1.0.beta41

https://github.com/zzlb0224/zotero-annotation-manage/assets/118701894/ed032d05-d08e-4528-993c-cd1d1d23caf8

**Comment by zzlb0224** [comment]
谢谢提供反馈。
