### ISSUE TITLE
修改标签后，格式比较乱，如何调整

### ISSUE THREAD

**Issue by hadoop78** [zzlb0224/zotero-annotation-manage#39]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/168334881/83c38745-f487-4c94-a693-901cb6a116bd)
这个格式比较乱，如何调整

**Comment by zzlb0224** [comment]
我改回原来的吧，这个是比较难看

**Comment by zzlb0224** [comment]
等更新

**Comment by hadoop78** [comment]
请问大约还有多久更新

**Comment by zzlb0224** [comment]
恢复成以前样式了
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/06b949e2-8626-4a71-88be-b88c1adad35d)

**Comment by hadoop78** [comment]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/168334881/0e73347d-b005-48fb-8d8e-20d47111478e)

![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/168334881/30777b53-7da8-47ea-bac2-ba9eaad73078)
我 试了试，重新卸载安装了，还是这个样子，是设置什么地方有问题吗

在Zotero设置窗口重载测试时，也发现数字和中文字不是一个，而是独立的两个选项了，点数字或点中文各有一个选中框

**Comment by hadoop78** [comment]
我 试了试，重新卸载安装了，还是这个样子，是设置什么地方有问题吗
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/168334881/74c446b7-1886-4c78-b952-6b8b187a9600)
在Zotero设置窗口重载测试时，也发现数字和中文字不是一个，而是独立的两个选项了，点数字或点中文各有一个选中框
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/168334881/94111410-acdc-444d-ab50-c27caaf68455)

**Comment by zzlb0224** [comment]
你试试这个选项
![Uploading image.png…]()

**Comment by hadoop78** [comment]
图没有上传成功，看不到

**Comment by zzlb0224** [comment]
固定标签使用独立样式

**Comment by hadoop78** [comment]
谢谢，把“固定标签使用独立样式”的勾选去除，就好了
