### ISSUE TITLE
弹出框字体和显示大小如何调整

### ISSUE THREAD

**Issue by linglinghahaha** [zzlb0224/zotero-annotation-manage#4]
插件功能很赞，但是显示格式如何调整好看一点呢？我没有找到调整的地方，使用说明里也没有。在装之前的显示
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/128910217/95aff703-919b-4760-a93e-bf45d6eb3aa3)
装完之后的显示，字体太大了，翻译结果显示到框外了
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/128910217/75a369fe-156e-4503-b2f2-5d0b530399a3)
另外下面一堆的tag，能不能设置哪些tag隐藏呢？

**Comment by zzlb0224** [comment]
设置功能我还没学会怎么实现。抱歉，等我学会了马上更新
字体大小 我想的是用 翻译插件的大小，读取它的配置，
tag以后会设置更多的自定义固定tag，并增加隐藏指定tag功能。

**Comment by llity** [comment]
宽度需要限制

**Comment by zzlb0224** [comment]
做了一个maxWidth
就是不是太大就是太小 :(

**Comment by llity** [comment]
> 做了一个maxWidth 就是不是太大就是太小 :(

应该width 100%？

**Comment by linglinghahaha** [comment]
> 设置功能我还没学会怎么实现。抱歉，等我学会了马上更新 字体大小 我想的是用 翻译插件的大小，读取它的配置， tag以后会设置更多的自定义固定tag，并增加隐藏指定tag功能。
隐藏指定tag功能什么时候能上线呀~别忘掉了啊

**Comment by zzlb0224** [comment]
> > 设置功能我还没学会怎么实现。抱歉，等我学会了马上更新 字体大小 我想的是用 翻译插件的大小，读取它的配置， tag以后会设置更多的自定义固定tag，并增加隐藏指定tag功能。
> > 隐藏指定tag功能什么时候能上线呀~别忘掉了啊

请问能不能说一下具体的操作方式？

**Comment by linglinghahaha** [comment]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/128910217/ef4c94fe-0526-48e8-8312-beb403438441)
如图片中的下面一堆类似格式的tag，其实是better note自动生成的一些链接，我不想在tag列表里出现。

**Comment by zzlb0224** [comment]
在排除标签中使用正则表达式

![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/f1cbbc40-6afb-471b-b1b2-18972e5bdc99)

**Comment by zzlb0224** [comment]
> ![image](https://private-user-images.githubusercontent.com/128910217/313455459-ef4c94fe-0526-48e8-8312-beb403438441.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjYyNzksIm5iZiI6MTcxMDcyNTk3OSwicGF0aCI6Ii8xMjg5MTAyMTcvMzEzNDU1NDU5LWVmNGM5NGZlLTA1MjYtNDhlOC04MzEyLWJlYjQwMzQzODQ0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMTM5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTAxMTQzYjBkZTJmNjQ0NTdiMWQxMjRkNjJhMmE1N2I3ZDE0YTNjNjk5MGQyMGEzZGVhN2MzMjNhZmQ3Yjg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IknQGXqRqAdPIFbFKaaCSB3v8oGL-hH8SOvZ9uWWmB4) 如图片中的下面一堆类似格式的tag，其实是better note自动生成的一些链接，我不想在tag列表里出现。

@linglinghahaha 已更新
