### ISSUE TITLE
与Translate for Zotero一起使用的时候，如果句子较长，对话框会显示在屏幕外

### ISSUE THREAD

**Issue by hahahacecilia** [zzlb0224/zotero-annotation-manage#46]
为了防止我没有描述清楚，截图如下：
![截屏2024-06-07 16 01 30 (2)](https://github.com/zzlb0224/zotero-annotation-manage/assets/106905636/63ca4ab2-6242-4957-8ef3-2f4f3151e6f5)

禁用[zotero-annotation-manage](https://github.com/zzlb0224/zotero-annotation-manage)，单独用Translate for Zotero的时候，就没有这个问题，显示效果如下：
![截屏2024-06-07 16 04 56 (2)](https://github.com/zzlb0224/zotero-annotation-manage/assets/106905636/5ac4a848-dfc3-46d2-9381-6f602912c1b6)

先前也没有这个困扰的，就是最近更新的版本（具体是从哪个版本开始出现的问题我也记不清了，因为我一直都跟着大佬的步伐更新的）才出现这个问题的。

不得不佩服大佬的频繁更新，如果能解决这个问题就更好啦！

再次感谢！

**Comment by hahahacecilia** [comment]
诶，单独使用Translate for Zotero可能也会出现这个问题o(╥﹏╥)o
我可能需要去Translate for Zotero的作者大佬那儿反馈一下这个问题。
<img width="1440" alt="截屏2024-06-07 16 14 11" src="https://github.com/zzlb0224/zotero-annotation-manage/assets/106905636/b133b47b-02ec-40c7-b969-93be198258a5">

**Comment by zzlb0224** [comment]
最新的zotero更新了能让颜色条在左右显示
我也没好的办法，如果有什么想法可以在这里提

**Comment by Kaergo** [comment]
就是这个插件导致的问题，关闭就不会导致。

**Comment by zzlb0224** [comment]
新版本使用新的弹出方式，正在改代码

**Comment by zzlb0224** [comment]
已经有了新的显示方式
