### ISSUE TITLE
请问我的这种图标签要怎么忽略？

### ISSUE THREAD

**Issue by Kaergo** [zzlb0224/zotero-annotation-manage#55]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/54634271/73975bfc-6cf3-48c3-8e1a-755d025a2058)
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/54634271/6c616d61-d642-4998-94b2-e0baec32c7ff)

**Comment by zzlb0224** [comment]
Figure \d+
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/e0f1128d-2a0d-4a2f-83c9-2c11ada961cc)

**Comment by Kaergo** [comment]
谢谢作者大大，请问不同的正则表达式之间是用换行间隔开吗？我这个标签没法忽略，请问要怎么解决呢。再次感谢作者大大开发这么好的插件。
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/54634271/9bcf71be-a942-48c1-a9f9-16f41d6a0918)

**Comment by zzlb0224** [comment]
不同的正则表达式之间是用换行间隔开
增加一行
Bi-directional linked annotation

**Comment by Kaergo** [comment]
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/54634271/1c482711-76dd-4ac8-bef3-7c0e469ec4d9)
好像还是去除不了。

**Comment by zzlb0224** [comment]
我测试了，好像有bug。我尽快修复下
