### ISSUE TITLE
希望可以添加按照指定的tag生成note的功能

### ISSUE THREAD

**Issue by Hongjing0506** [zzlb0224/zotero-annotation-manage#7]
现在条目的右键菜单中，【导出笔记】里有一个【tag:量表】选项，点击的时候会搜索【量表】这个tag然后生成笔记。但是没有找到在哪里可以自定义这个标签，感觉是这个功能还没有做完？
希望后面可以添加：按照指定的tag（每次点击的时候进行询问），提取annotations作为笔记（如果可以单pdf提取或多pdf同时提取并排序更好）的功能。

谢谢开发这个插件！

**Comment by zzlb0224** [comment]
这个是我做这个插件的初衷。我是想要什么格式就自己加个菜单。其它格式欢迎提想法

**Comment by Hongjing0506** [comment]
有了，更新真快！谢谢！
另外发现生成的笔记中，annotation内容会是Heading2等级，这个能设置成普通的paragraph吗？

**Comment by zzlb0224** [comment]
> 有了，更新真快！谢谢！ 另外发现生成的笔记中，annotation内容会是Heading2等级，这个能设置成普通的paragraph吗？

自定义导出设置为段落吧。
