### ISSUE TITLE
请问这两个图标如何使用

### ISSUE THREAD

**Issue by LiuJ00** [zzlb0224/zotero-annotation-manage#76]
![CleanShot 2024-07-23 at 15 23 23@2x](https://github.com/user-attachments/assets/a7f8ddc7-e9ee-41e0-abf3-09f1ff04e9d4)
请问这两个图标如何使用？
zotero7 beta.105
插件版本0.6.107

**Comment by zzlb0224** [comment]
一个是做多词组查找，颜色老是定位不了（还没做完）
![image](https://github.com/user-attachments/assets/cb3fab2e-b301-421a-81d2-dd11a9ccd9ad)


还有一个是显示参考文献的查询按钮（时灵时不灵）
![image](https://github.com/user-attachments/assets/56114bd0-0109-41cf-b553-655d63815dd5)
