### ISSUE TITLE
多选annotations进行tag编辑（tag）时，可以同时添加某tag，但添加后无法同时删除

### ISSUE THREAD

**Issue by Hongjing0506** [zzlb0224/zotero-annotation-manage#8]
如题，多选annotation进行tag编辑的时候，点击某个tag可以为它们同时添加上tag。但是再次点击已添加的tag进行取消tag时，则只能取消其中一个annotation的tag，而不是所有选中的annotations的tag都取消。

最后，谢谢你开发这个插件！

**Comment by zzlb0224** [comment]
以前的功能是：
1、如果全部都没有则添加
2、如果其中一个或者多个annotation有，那么其它的都加上
3、如果全部都有，那么就取消。

我个人觉得这个不好理解，容易误操作，所以把3给取消了
还没想好怎么改
未来打算在弹出框里面显示已经有的tag，选中的tag取消。

**Comment by zzlb0224** [comment]
已经更新，选中后保存可以删除
![image](https://github.com/zzlb0224/zotero-annotation-manage/assets/8912444/3f752a77-63e9-478d-8805-36dfadaf3c44)
