### ISSUE TITLE
修改了两个继承之后立马变成空白，一直使用我的文库的配置，无法修改下级组别的标签配置

### ISSUE THREAD

**Issue by oushiei120** [zzlb0224/zotero-annotation-manage#84]
<img width="815" alt="截屏2024-08-04 16 43 36" src="https://github.com/user-attachments/assets/16d76329-125e-4a72-b061-1733ca8a910a">
如图所示。

**Comment by zzlb0224** [comment]
收到

**Comment by zzlb0224** [comment]
已更新
