### ISSUE TITLE
预览导出的注释内容显示不全

### ISSUE THREAD

**Issue by logseq20182018** [zzlb0224/zotero-annotation-manage#93]
1.希望可以增加窗口拖动条
2.希望右键可以复制注释的md外链，方便插入其它笔记中

![image](https://github.com/user-attachments/assets/c9493696-9c15-4dd6-977a-7783e24f6ec3)

**Comment by zzlb0224** [comment]
修改了overflow。鼠标悬停可以上下滚动

也可以调整 行 列 和字体大小试试

**Comment by logseq20182018** [comment]
> 修改了overflow。鼠标悬停可以上下滚动
> 
> 也可以调整 行 列 和字体大小试试

谢谢！你是指的这样吗？
![image](https://github.com/user-attachments/assets/d37eb1d8-dd27-485a-a452-d568ea2029d6)
可以添加拖动条吗？

**Comment by logseq20182018** [comment]
> 修改了overflow。鼠标悬停可以上下滚动
> 
> 也可以调整 行 列 和字体大小试试

![image](https://github.com/user-attachments/assets/aeee45fb-bff5-4332-9aad-eb221d2a70be)
其实style本身的注释挺简洁的，就是没得你这个筛选功能丰富

**Comment by zzlb0224** [comment]
我加上自定义选项，可以显示/隐藏 标题、期刊等级、tag，这样也能达到这个简洁的效果

**Comment by logseq20182018** [comment]
> 我加上自定义选项，可以显示/隐藏 标题、期刊等级、tag，这样也能达到这个简洁的效果

是还没加？感觉你更新的这两版跟之前没区别呢？
![image](https://github.com/user-attachments/assets/9c63f723-510e-479e-9a8c-72c5593a9eab)

**Comment by zzlb0224** [comment]
我还没做呢。

**Comment by logseq20182018** [comment]
> 我还没做呢。

好的，加油加油

**Comment by zzlb0224** [comment]
加了一个不固定高度，和标题的显示隐藏功能。
